controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_exchange:
    path: /exchange/values
    controller: App\Controller\ApiExchangeController::exchangeValues
    methods: [POST]

api_exchange_history_show_all_records:
    path: /exchange/history/showAllRecords
    controller: App\Controller\ApiExchangeController::getShowAllRecordsFromHistory
    methods: [GET, POST]
