controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_exchange:
    path: /exchange/values
    controller: App\Controller\ApiExchangeController::exchangeValues
    methods: [POST]