controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_exchange:
    path: /api/exchange
    controller: App\Controller\ApiExchangeController::index
    methods: [POST]